version: '3.7'

# This docker-compose.yml file is meant for development only.
services:
  php:
    image: ${APP_NAME}:latest
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${APP_NAME}-php
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mysql

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: ${APP_NAME}-nginx
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - "8080:80"
      - "443:443"

  mysql:
    image: mysql:8.0
    container_name: ${APP_NAME}-mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/entrypoint:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: development
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - ${DATABASE_EXTERNAL_PORT:-3306}:${DATABASE_PORT}

volumes:
  mysql-data:
